"""
Dynamic criteria generation — v0.9.0

When genre detection confidence is below threshold or the genre is classified
as "mixed", this module generates evaluation criteria tailored to the specific
text rather than relying on static genre dimension sets.

The criteria generation prompt asks the model to read the text and propose
5 evaluation dimensions specific to THIS text — what matters most for
reviewing THIS particular piece, given its form, ambitions, and methods.

Each generated criterion becomes a dimension prompt that runs in parallel,
just like static genre dimensions. The synthesis then uses a genre-agnostic
prompt designed to work with whatever criteria were generated.

Design principle: The dynamic path should produce feedback of comparable
depth to the static path. This means the criteria generation prompt must
elicit DEEP, SPECIFIC criteria — not thin category labels. Each criterion
needs enough analytical intelligence that the resulting dimension review
can be substantive.
"""

import json
from typing import Dict, List, Optional


# ── Criteria generation prompt ──────────────────────────────────

CRITERIA_GENERATION_SYSTEM = """You are an expert editorial analyst. Your job is to read a piece of writing and determine the 5 most important dimensions on which it should be evaluated.

You are NOT reviewing the text yet. You are designing a review framework for it — deciding WHAT to examine, not delivering verdicts.

IMPORTANT CONSTRAINTS:

1. Your criteria must be SPECIFIC TO THIS TEXT. "Clarity of argument" is too generic — it could apply to anything. "Whether the essay's central metaphor of inheritance can sustain the weight of both its legal and emotional registers" is specific.

2. Each criterion must identify a GENUINE ANALYTICAL QUESTION about the text — something where a thoughtful reviewer would need to read carefully to reach a judgment. Not a box to check, but a dimension where the text could succeed or fail in interesting ways.

3. Your criteria should cover DIFFERENT LEVELS of the text:
   - At least one criterion about the text's conceptual architecture (big-picture structure, central moves, governing logic)
   - At least one about its use of evidence, examples, or source material
   - At least one about a specific technique, method, or formal choice the text employs
   - The remaining criteria should address whatever is most important for THIS text

4. Do NOT include criteria about prose style, readability, sentence flow, or grammar unless the text's style IS its primary method (e.g., a prose poem where rhythm carries meaning).

5. Do NOT include a generic "strengths and weaknesses" criterion. Every criterion should be substantive.

6. Each criterion's description must give the reviewer enough analytical intelligence to produce a deep review. Include:
   - What specifically to look for
   - What would constitute success vs. failure on this dimension
   - Any traps or subtleties the reviewer should watch for (e.g., "apparent inconsistency may be deliberate — check whether...")

OUTPUT FORMAT: A single JSON object with this structure:

{
  "criteria": [
    {
      "name": "Short descriptive name (3-8 words)",
      "key": "snake_case_key",
      "description": "2-4 sentence description of what to examine and why it matters for this text. Include specific analytical guidance.",
      "priority": 1
    }
  ],
  "rationale": "1-2 sentences explaining why these criteria suit this particular text."
}

You must output exactly 5 criteria. Do not output any other text."""


CRITERIA_GENERATION_USER = """Read the following text carefully, then design 5 evaluation criteria specific to it.

Consider: What genre or form is this text operating in? What are its central ambitions? What methods does it use? Where are the high-stakes moments where it could succeed or fail? What would a thoughtful, expert reviewer most need to examine?

If the text blends genres or forms (e.g., a memoir that also advances a political argument, a piece of criticism that uses narrative techniques), your criteria should reflect that hybridity — not force the text into a single genre's expectations.

---
{essay_text}
---

Design 5 evaluation criteria for this text. Output ONLY the JSON object."""


# ── Dynamic dimension prompt builder ────────────────────────────

DYNAMIC_DIMENSION_TEMPLATE = """Your focus: {description}

You are reviewing this specific text against a criterion that was designed for it. This is not a generic rubric — the criterion was generated by reading this text and identifying what matters most for evaluating it.

CRITERION: {name}

WHAT TO EXAMINE:
{description}

For each issue you find:
1. Quote the relevant passages (keep each quote under 40 words)
2. Explain the specific issue — what the text does, what it should do, and why the gap matters
3. Assess how seriously this affects the text's success
4. Where possible, suggest how the author might resolve it using the text's OWN materials — existing evidence, arguments, examples, or structural moves that could be redeployed

Write your response as thematic paragraphs, each addressing a distinct observation. Include every observation that meets the quality threshold — whether that's 2 or 8. Write in analytical prose, not bullet-point lists. You may use a brief severity note (CRITICAL/MODERATE) at the start of each paragraph.

QUALITY THRESHOLD: Every observation must concern the text's substance — its argument, evidence, claims, methods, form, or conceptual architecture. Do NOT include observations about prose style, sentence flow, or readability unless the style issue creates a substantive problem."""


# ── Dynamic synthesis prompt ────────────────────────────────────

DYNAMIC_SYNTHESIS_PROMPT = """You are a senior editor producing a final review report for a piece of writing. You are synthesising findings from {num_reviews} parallel analytical reviews, each examining a different dimension of the text. These dimensions were generated specifically for THIS text — they are not a generic rubric.

Your task is to produce a review with TWO clearly distinct sections:

---

## Overall Feedback

Write a brief introduction ("Here are some overall reactions to the document."), then immediately provide:

**Strengths**: A paragraph identifying what the text does well (be specific, with examples). Lead with this so the author reads your positive assessment before the critique.

Then produce thematic essays, each 100-200 words, addressing the text's most significant issues. Include every cross-cutting issue that concerns the text's substance — whether that's 3 or 8. These should read like the feedback a rigorous editor would provide — substantive intellectual engagement, not a checklist.

Each thematic essay should:
- Have a bolded descriptive title
- Identify a cross-cutting issue that affects multiple parts of the text
- Reference specific sections or passages to anchor the observation
- Explain why this matters for the text's success
- Suggest how to resolve the issue — framed in terms of the text's OWN materials. Show the author how their existing evidence, examples, or structural moves can be redeployed more effectively.

After the thematic essays, include:
- A **Top 5 Priority Actions** numbered list — the five most important changes the author should make, in order of impact

---

## Detailed Comments

Select every specific, localised issue that concerns the text's substance — things a careful reader would stumble over. These should be DIFFERENT from the thematic issues above (which are cross-cutting). These are precise, surgical observations about specific passages.

Format each as:

### [Number]. [Short descriptive title]

**Status**: [Pending]

**Quote**:
> [exact quoted text from the essay — enough context for the author to locate it]

**Feedback**:
[Your specific observation and suggestion. Where possible, ground the suggestion in the text's own materials.]

---

CRITICAL RULES FOR THIS REVIEW:
1. SUBSTANCE ONLY. Every observation must concern the text's argument, evidence, claims, methods, form, or conceptual architecture. Do NOT include observations about prose style, sentence flow, or readability — unless a style issue creates a substantive problem.
2. ENGAGE WITH THE TEXT ON ITS OWN TERMS. Understand what the text is trying to do and assess it against its own ambitions, not a generic standard.
3. NO FALSE FLAGS. If the text describes events that contradict your training knowledge, assume the text is correct and your knowledge is outdated. Do NOT flag recent events as errors. A false flag destroys the review's credibility.
4. NO GENERIC ADVICE. Every suggestion must be specific to THIS text.
5. EXACT QUOTES in Detailed Comments.
6. THEMATIC ESSAYS IN PROSE — connected analytical paragraphs, not bullet-point lists.
7. RESPECT THE REGISTER. Do not suggest hedging that would flatten the author's voice. If the text operates in an essayistic register, rhetorical conviction is a feature.
8. ARGUMENT-INTERNAL FRAMING. Frame suggestions in terms of how the text's own materials can be deployed more effectively.
9. NO DUPLICATE ACTIONS. Each priority action must address a distinct issue.

ORIGINAL TEXT:
{essay_text}

REVIEW OUTPUTS:
{reviews}

Generate the complete report now."""


DYNAMIC_SYNTHESIS_SYSTEM_MESSAGE = """You are a senior editor producing a final review of a serious piece of writing. You combine intellectual rigour with constructive engagement. You write in analytical prose, not bullet-point checklists. Every observation you make is anchored to specific text and explains why it matters. You engage with the text on its own terms — your suggestions show how the text's own evidence and moves can be deployed more effectively, not what it gets wrong from an external vantage point. You read as a serious intellectual partner who wants the text to succeed."""


# ── Hybrid synthesis preamble ───────────────────────────────────
# Injected when synthesis receives dimensions from both static genre
# AND dynamic criteria paths.

HYBRID_SYNTHESIS_BLOCK = """
HYBRID REVIEW CONTEXT:

This text has been reviewed through TWO complementary lenses:
1. GENRE DIMENSIONS ({genre}): Standard editorial dimensions calibrated for {genre} writing — these catch the issues that experienced editors of this form know to look for.
2. DYNAMIC CRITERIA: Evaluation dimensions generated specifically for THIS text — these catch what's distinctive about this particular piece that genre conventions alone might miss.

When synthesising:
- Draw on BOTH dimension sets to produce a unified review. Do not separate feedback by source.
- Where both lenses identify the same issue, synthesise into a single, richer observation.
- Where one lens catches something the other misses, include both — these complementary insights are the value of hybrid analysis.
- PRESERVE THE STRONGEST UNIQUE OBSERVATIONS from each set. Before synthesising, identify the single most valuable observation from each dynamic criterion that does NOT duplicate anything in the genre dimensions. These unique catches justify the hybrid approach.
- Do NOT penalise the text for not conforming to a single framework. The hybrid approach exists precisely because this text is doing something that benefits from multiple analytical perspectives.
"""


# ── Parsing and conversion ──────────────────────────────────────

def parse_criteria_response(text: str) -> Optional[List[Dict]]:
    """
    Parse criteria generation JSON response.

    Returns a list of criterion dicts, or None on failure.
    Each criterion has: name, key, description, priority.
    """
    try:
        cleaned = text.strip()
        if cleaned.startswith("```"):
            cleaned = cleaned.split("\n", 1)[1]
            if cleaned.endswith("```"):
                cleaned = cleaned[: cleaned.rfind("```")]
            cleaned = cleaned.strip()

        data = json.loads(cleaned)
        criteria = data.get("criteria", [])

        if not criteria or not isinstance(criteria, list):
            return None

        validated = []
        for i, c in enumerate(criteria):
            name = str(c.get("name", f"Criterion {i+1}"))
            key = str(c.get("key", f"dynamic_criterion_{i+1}"))
            # Sanitise key
            key = key.lower().replace(" ", "_").replace("-", "_")
            # Ensure no duplicate keys
            existing_keys = [v["key"] for v in validated]
            if key in existing_keys:
                key = f"{key}_{i+1}"

            description = str(c.get("description", ""))
            priority = int(c.get("priority", i + 1))

            if not description:
                continue

            validated.append({
                "name": name,
                "key": key,
                "description": description,
                "priority": priority,
            })

        return validated if validated else None

    except (json.JSONDecodeError, KeyError, TypeError, ValueError):
        return None


def criteria_to_dimension_prompts(criteria: List[Dict]) -> Dict:
    """
    Convert generated criteria into the standard DIMENSION_PROMPTS format
    used by the pipeline.

    Each criterion becomes a dimension prompt dict with 'name', 'priority',
    and 'prompt' keys — the same interface as static genre dimension prompts.

    Args:
        criteria: List of criterion dicts from parse_criteria_response()

    Returns:
        Dict mapping dimension keys to prompt dicts, compatible with
        the pipeline's load_genre_prompts() return format.
    """
    dimension_prompts = {}

    for criterion in criteria:
        key = criterion["key"]
        prompt_text = DYNAMIC_DIMENSION_TEMPLATE.format(
            name=criterion["name"],
            description=criterion["description"],
        )

        dimension_prompts[key] = {
            "name": criterion["name"],
            "priority": criterion["priority"],
            "prompt": prompt_text,
        }

    return dimension_prompts
